language: objective-c
osx_image: xcode10.1
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=CRDSettings.xcodeproj
  - IOS_SCHEME="CRDSettings"
  - IOS_SCHEME_APP="CRDSettingsTestApp"
  - IOS_SDK=iphonesimulator12.1
  matrix:
    - DESTINATION="name=iPhone X" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" RUN_TESTS="NO" POD_LINT="NO"
    - DESTINATION="name=iPhone X" SCHEME="$IOS_SCHEME_APP" SDK="$IOS_SDK" RUN_TESTS="NO" POD_LINT="NO"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ "$RUN_TESTS" == "YES" ]; then xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test; else xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build; fi

  # Run pod lib lint if specified
  - if [ "$POD_LINT" == "YES" ]; then pod lib lint --private --verbose; fi
